# Generated by Django 2.2.26 on 2022-01-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='book_type',
            field=models.CharField(blank=True, choices=[('default', 'default')], max_length=256, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='flipbookdownload',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('video', 'Video')], max_length=12, verbose_name='File type'),
        ),
        migrations.AlterField(
            model_name='flipbookpage',
            name='page_type',
            field=models.CharField(blank=True, choices=[('default', 'default')], max_length=256, verbose_name='Type'),
        ),
    ]
