# Generated by Django 2.2.26 on 2022-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbook', '0002_auto_20220118_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbook',
            name='download_link',
            field=models.URLField(blank=True, verbose_name='Download Link'),
        ),
    ]
