# Generated by Django 2.2.26 on 2022-09-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbook', '0003_flipbook_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbookdownload',
            name='download_link',
            field=models.URLField(blank=True, verbose_name='Download Link'),
        ),
    ]
