# Generated by Django 2.2.28 on 2024-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbook', '0005_flipbook_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
    ]
